# Generated by Django 5.0.6 on 2024-06-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_image', models.ImageField(upload_to='images/')),
                ('classes_topic', models.CharField(max_length=100)),
                ('classes_details', models.CharField(max_length=100)),
            ],
        ),
    ]
