# Generated by Django 5.0.6 on 2024-06-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classes_details',
            field=models.CharField(max_length=300),
        ),
    ]
